/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superDeTodo;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafa
 */
public class BusquedaPorPrecio extends javax.swing.JInternalFrame {
private DefaultTableModel modelo = new DefaultTableModel();
    
   public boolean isCellEditable(int f,int c){
   return false;
   }

/**
     * Creates new form BusquedaPorNombreView
     */
    public BusquedaPorPrecio() {
        initComponents();
        armarCabecera(); //lLAMA AL METODO DE ABAJO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtMinimo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtMaximo = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Busqueda por nombre");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Listado por Precio");

        jLabel2.setText("Entre");

        jtMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMinimoActionPerformed(evt);
            }
        });
        jtMinimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtMinimoKeyReleased(evt);
            }
        });

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtProductos);

        jLabel3.setText("y");

        jtMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMaximoActionPerformed(evt);
            }
        });
        jtMaximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtMaximoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMinimoActionPerformed

    private void jtMinimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMinimoKeyReleased
borrarFilas();
double precioMinimo = 0,precioMaximo=0;

try{

if(jtMinimo.getText().isEmpty()){
  precioMinimo=0;
}else{
precioMinimo=Double.parseDouble(jtMinimo.getText());
}

if(jtMaximo.getText().isEmpty()){
  precioMaximo=Double.POSITIVE_INFINITY; 
}else{
precioMaximo=Double.parseDouble(jtMaximo.getText());
}
}catch(Exception e){
    System.out.println("Ocurrio un error: "+e.getMessage());
}

        for (Producto pro:MenuPrincipal.listaProductos) {
            if(pro.getPrecio()>=precioMinimo&& pro.getPrecio()<=precioMaximo){
                
                 modelo.addRow(new Object []{ //Agrega una fila pero coo una fila de objetos
                 pro.getCodigo(),
                     pro.getDescripcion(),
                     pro.getPrecio(),
                     pro.getStock(),
                 
                 
                 });
                 
            }
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMinimoKeyReleased

    private void jtMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMaximoActionPerformed

    private void jtMaximoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMaximoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMaximoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtMaximo;
    private javax.swing.JTextField jtMinimo;
    private javax.swing.JTable jtProductos;
    // End of variables declaration//GEN-END:variables

private void armarCabecera(){
 modelo.addColumn("Codigo");
 modelo.addColumn("Descripciòn");
 modelo.addColumn("Precio");
 modelo.addColumn("Stock");
 jtProductos.setModel(modelo);
 
  }

private void borrarFilas(){
  int filas=jtProductos.getRowCount()-1;
  for(;filas>=0;filas--){
  modelo.removeRow(filas);
  }
}

}