/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superDeTodo;

import java.util.TreeSet;

/**
 *
 * @author rafa
 */
public class MenuPrincipal extends javax.swing.JFrame {
public static TreeSet<Producto>listaProductos=new TreeSet<>();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        cargarProductos();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jdesktopEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdministracion = new javax.swing.JMenu();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemRubro = new javax.swing.JMenuItem();
        jMenuItemNombre = new javax.swing.JMenuItem();
        jMenuItemPrecio = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supermercado \"DeTodo SA\"");
        setPreferredSize(new java.awt.Dimension(670, 600));

        jdesktopEscritorio.setPreferredSize(new java.awt.Dimension(670, 579));

        javax.swing.GroupLayout jdesktopEscritorioLayout = new javax.swing.GroupLayout(jdesktopEscritorio);
        jdesktopEscritorio.setLayout(jdesktopEscritorioLayout);
        jdesktopEscritorioLayout.setHorizontalGroup(
            jdesktopEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jdesktopEscritorioLayout.setVerticalGroup(
            jdesktopEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuAdministracion.setText("Administrcion");

        jMenuItemProductos.setText("Productos");
        jMenuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductosActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuItemProductos);

        jMenuBar1.add(jMenuAdministracion);

        jMenuConsultas.setText("Consultas");

        jMenuItemRubro.setText("Por Rubro");
        jMenuItemRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRubroActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemRubro);

        jMenuItemNombre.setText("Por Nombre");
        jMenuItemNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNombreActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemNombre);

        jMenuItemPrecio.setText("Por Precio");
        jMenuItemPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrecioActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemPrecio);

        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesktopEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesktopEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRubroActionPerformed
        jdesktopEscritorio.removeAll();
      jdesktopEscritorio.repaint();
      BusquedaPorRubro bpn= new BusquedaPorRubro();
      bpn.setVisible(true);
      jdesktopEscritorio.add(bpn);
      jdesktopEscritorio.moveToFront(bpn);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRubroActionPerformed

    private void jMenuItemNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNombreActionPerformed
      jdesktopEscritorio.removeAll();
      jdesktopEscritorio.repaint();
      BusquedaPorNombreView bpn= new BusquedaPorNombreView();
      bpn.setVisible(true);
      jdesktopEscritorio.add(bpn);
      jdesktopEscritorio.moveToFront(bpn);
    }//GEN-LAST:event_jMenuItemNombreActionPerformed

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosActionPerformed
       //Para traer al frente una ventana
       jdesktopEscritorio.removeAll();
      jdesktopEscritorio.repaint();
//      BusquedaPorNombreView bpn= new BusquedaPorNombreView();
        MenuProductos mp = new MenuProductos ();
      mp.setVisible(true);
      jdesktopEscritorio.add(mp);
      jdesktopEscritorio.moveToFront(mp);
    }//GEN-LAST:event_jMenuItemProductosActionPerformed

    private void jMenuItemPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrecioActionPerformed
       jdesktopEscritorio.removeAll();
      jdesktopEscritorio.repaint();
      BusquedaPorPrecio bpn= new BusquedaPorPrecio();
      bpn.setVisible(true);
      jdesktopEscritorio.add(bpn);
      jdesktopEscritorio.moveToFront(bpn); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemNombre;
    private javax.swing.JMenuItem jMenuItemPrecio;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenuItem jMenuItemRubro;
    private javax.swing.JDesktopPane jdesktopEscritorio;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos(){
    listaProductos.add(new Producto(10,"Azucar",180,75,"Comestible"));
    listaProductos.add(new Producto(12,"Lavandina",200,25,"Limpieza"));
    listaProductos.add(new Producto(131,"Aceite",500,10,"Comestible"));
    }

}


